### ISSUE TITLE
Button missing on the windows7 looking skin

### ISSUE THREAD

**Issue by abrildn** [AlexHaible/BetterBags-Themes#1]
Hi, on this skin the button that goes on the top left corner that lets you change theme and stuff is not there. Tried clicking everywhere to see if it was hidden but couldn't find it. Therefore I can't change the skin back and also can't automatically add all reagents/warband stuff to the bank either

**Comment by AlexHaible** [comment]
That'd be because it's the maximize button. I know it doesn't _really_ make sense, but I was limited in what buttons would fit in with the theme. I can assure you it's there though.
